### ISSUE TITLE
ActiveIndex should be an array and handle multiples values in it.

### ISSUE THREAD

**Issue by saboco** [fable-compiler/fable-recharts#8]
I'm moving the discussion here as the PR for `sample2` it's already merged.

---

`ActiveIndex` was an `Array` before. The problem is that `ActiveShape` wasn't being fired in the initial load. Also while working with array it only works with one value in it, passing two or more prevents the `ActiveShape` to be fired.

Changing the type of `ActiveIndex` from `Array` to `int` gets the whole thing working.

The problem is that `recharts` accepts also an `Array` of `number` so several `shapes` can be active at the same time and `ActiveShape` will be fired for each index in the array

I'm not sure on how to debug this, so if you have some tips so I can help it would be great.

**Comment by alfonsogarciacaro** [comment]
Ok, I found the problem. This is because Fable compiles numeric arrays to JS typed arrays, and these are not recognized by Recharts. There are a couple of solutions to this I can think of at the moment:

- Use `typedArrays: false` option in fable-loader. But users need to remember this.
- Make Fable convert typed arrays into standard JS arrays when being casted to `System.Array`. But that may be a solution too specific for this case, it won't work any more if the signature changes to `ActiveIndex of int[]` (In that case you need to use `ResizeArray<int>`).

🤔

**Comment by alfonsogarciacaro** [comment]
Ok, I've opted for the 2nd option :) This will be included in the next release of fable-compiler.

**Comment by saboco** [comment]
@alfonsogarciacaro that was quick, thank you.
Do you mind sharing why did you choose the second option?

**Comment by alfonsogarciacaro** [comment]
Because the first solution depends on a compiler flag. I added that one at the very beginning, but I don't like very much compiler flags because it means you need to find the right combination to get what you need and also from the maintenance point of view, you have to support multiple outputs. Having the same standard behavior for everybody is simpler :)

**Comment by alfonsogarciacaro** [comment]
Unfortunately my solution is creating other problems :/ https://github.com/fable-compiler/Fable/issues/1896

I'll have to revert the change in the compiler and in order to avoid problems with the bindings we should use `ResizeArray<int>` or `ResizeArray<obj>` which will always compile to a dynamic JS array (not typed).

**Comment by saboco** [comment]
No problem at all. 
It worked just fine with `ResizeArray<int>`
